--- 
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: archspec-feature-discovery
  namespace: archspec-feature-discovery
  labels:
    app.kubernetes.io/name: archspec-feature-discovery
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: archspec-feature-discovery
  template:
    metadata:
      labels:
        app.kubernetes.io/name: archspec-feature-discovery
    spec:
      containers:
        - image: quay.io/eduardoarango/archspec-feature-discovery:latest
          name: archspec-feature-discovery
          volumeMounts:
            - name: output-dir
              mountPath: "/etc/kubernetes/node-feature-discovery/features.d"
          securityContext:
            privileged: true
      serviceAccount: archspec-feature-discovery
      volumes:
        - name: output-dir
          hostPath:
            path: "/etc/kubernetes/node-feature-discovery/features.d"
      nodeSelector:
        node-role.kubernetes.io/worker: ""
